<?php

use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->delete();

        $countries = array(
            array('country_code' => 'US', 'country_name' => 'الولايات المتحدة الأمريكية'),
            array('country_code' => 'CA', 'country_name' => 'كندا'),
            array('country_code' => 'AF', 'country_name' => 'أفغانستان') ,
            array('country_code' => 'AL', 'country_name' => 'ألبانيا') ,
            array('country_code' => 'DZ', 'country_name' => 'الجزائر'),
            array('country_code' => 'AS', 'country_name' => 'ساموا الأمريكية'),
            array('country_code' => 'AD', 'country_name' => 'أندورا') ,
            array('country_code' => 'AO', 'country_name' => 'أنجولا') ,
            array('country_code' => 'AI', 'country_name' => 'أنغيلا') ,
            array('country_code' => 'AQ', 'country_name' => 'أنتاركتيكا') ,
            array('country_code' => 'AG', 'country_name' => 'أنتيغوا و / أو باربودا') ,
            array('country_code' => 'AR', 'country_name' => 'الأرجنتين') ,
            array('country_code' => 'AM', 'country_name' => 'أرمينيا') ,
            array('country_code' => 'AW', 'country_name' => 'أروبا') ,
            array('country_code' => 'AU', 'country_name' => 'أستراليا') ,
            array('country_code' => 'AT', 'country_name' => 'النمسا') ,
            array('country_code' => 'AZ', 'country_name' => 'أذربيجان'),
            array('country_code' => 'BS', 'country_name' => 'جزر البهاما') ,
            array('country_code' => 'BH', 'country_name' => 'البحرين'),
            array('country_code' => 'BD', 'country_name' => 'بنغلاديش') ,
            array('country_code' => 'BB', 'country_name' => 'بربادوس') ,
            array('country_code' => 'BY', 'country_name' => 'بيلاروس') ,
            array('country_code' => 'BE', 'country_name' => 'بلجيكا') ,
            array('country_code' => 'BZ', 'country_name' => 'بليز') ,
            array('country_code' => 'BJ', 'country_name' => 'بنين') ,
            array('country_code' => 'BM', 'country_name' => 'برمودا') ,
            array('country_code' => 'BT', 'country_name' => 'بوتان') ,
            array('country_code' => 'BO', 'country_name' => 'بوليفيا') ,
            array('country_code' => 'BA', 'country_name' => 'البوسنة والهرسك'),
            array('country_code' => 'BW', 'country_name' => 'بوتسوانا') ,
            array('country_code' => 'BV', 'country_name' => 'جزيرة بوفيت') ,
            array('country_code' => 'BR', 'country_name' => 'البرازيل'),
            array('country_code' => 'IO', 'country_name' => 'إقليم المحيط الهندي البريطاني') ,
            array('country_code' => 'BN', 'country_name' => 'بروناي دار السلام'),
            array('country_code' => 'BG', 'country_name' => 'بلغاريا') ,
            array('country_code' => 'BF', 'country_name' => 'بوركينا فاسو'),
            array('country_code' => 'BI', 'country_name' => 'بوروندي') ,
            array('country_code' => 'KH', 'country_name' => 'كمبوديا') ,
            array('country_code' => 'CM', 'country_name' => 'الكاميرون') ,
            array('country_code' => 'CV', 'country_name' => 'الرأس الأخضر') ,
            array('country_code' => 'KY', 'country_name' => 'جزر كايمان') ,
            array('country_code' => 'CF', 'country_name' => 'جمهورية افريقيا الوسطى'),
            array('country_code' => 'TD', 'country_name' => 'تشاد') ,
            array('country_code' => 'CL', 'country_name' => 'تشيلي') ,
            array('country_code' => 'CN', 'country_name' => 'الصين'),
            array('country_code' => 'CX', 'country_name' => 'جزيرة الكريسماس') ,
            array('country_code' => 'CC', 'country_name' => 'جزر كوكوس (كيلنج)' ),
            array('country_code' => 'CO', 'country_name' => 'كولومبيا') ,
            array('country_code' => 'KM', 'country_name' => 'جزر القمر') ,
            array('country_code' => 'CG', 'country_name' => 'الكونغو') ,
            array('country_code' => 'CK', 'country_name' => 'جزر كوك'),
            array('country_code' => 'CR', 'country_name' => 'كوستا ريكا'),
            array('country_code' => 'HR', 'country_name' => 'كرواتيا (Hrvatska)') ,
            array('country_code' => 'CU', 'country_name' => 'كوبا') ,
            array('country_code' => 'CY', 'country_name' => 'قبرص') ,
            array('country_code' => 'CZ', 'country_name' => 'جمهورية التشيك'),
            array('country_code' => 'CD', 'country_name' => 'جمهورية الكونغو الديمقراطية') ,
            array('country_code' => 'DK', 'country_name' => 'الدنمارك') ,
            array('country_code' => 'DJ', 'country_name' => 'جيبوتي') ,
            array('country_code' => 'DM', 'country_name' => 'دومينيكا') ,
            array('country_code' => 'DO', 'country_name' => 'جمهورية الدومنيكان'),
            array('country_code' => 'TP', 'country_name' => 'تيمور الشرقية'),
            array('country_code' => 'EC', 'country_name' => 'إيكودور') ,
            array('country_code' => 'EG', 'country_name' => 'مصر') ,
            array('country_code' => 'SV', 'country_name' => 'السلفادور'),
            array('country_code' => 'GQ', 'country_name' => 'غينيا الإستوائية'),
            array('country_code' => 'ER', 'country_name' => 'إريتريا') ,
            array('country_code' => 'EE', 'country_name' => 'إستونيا') ,
            array('country_code' => 'ET', 'country_name' => 'أثيوبيا'),
            array('country_code' => 'FK', 'country_name' => 'جزر فوكلاند (مالفيناس)') ,
            array('country_code' => 'FO', 'country_name' => 'جزر فاروس'),
            array('country_code' => 'FJ', 'country_name' => 'فيجي') ,
            array('country_code' => 'FI', 'country_name' => 'فنلندا') ,
            array('country_code' => 'FR', 'country_name' => 'فرنسا'),
            array('country_code' => 'FX', 'country_name' => 'فرنسا , متروبوليتان') ,
            array('country_code' => 'GF', 'country_name' => 'غيانا الفرنسية'),
            array('country_code' => 'PF', 'country_name' => 'بولينيزيا الفرنسية'),
            array('country_code' => 'TF', 'country_name' => 'المناطق الجنوبية لفرنسا'),
            array('country_code' => 'GA', 'country_name' => 'غابون') ,
            array('country_code' => 'GM', 'country_name' => 'غامبيا') ,
            array('country_code' => 'GE', 'country_name' => 'جورجيا') ,
            array('country_code' => 'DE', 'country_name' => 'ألمانيا'),
            array('country_code' => 'GH', 'country_name' => 'غانا') ,
            array('country_code' => 'GI', 'country_name' => 'جبل طارق') ,
            array('country_code' => 'GR', 'country_name' => 'اليونان'),
            array('country_code' => 'GL', 'country_name' => 'الأرض الخضراء'),
            array('country_code' => 'GD', 'country_name' => 'غرينادا') ,
            array('country_code' => 'GP', 'country_name' => 'جوادلوب') ,
            array('country_code' => 'GU', 'country_name' => 'غوام') ,
            array('country_code' => 'GT', 'country_name' => 'غواتيمالا') ,
            array('country_code' => 'GN', 'country_name' => 'غينيا') ,
            array('country_code' => 'GW', 'country_name' => 'غينيا بيساو') ,
            array('country_code' => 'GY', 'country_name' => 'جويانا') ,
            array('country_code' => 'HT', 'country_name' => 'هايتي') ,
            array('country_code' => 'HM', 'country_name' => 'جزر هيرد وماكدونالد') ,
            array('country_code' => 'HN', 'country_name' => 'هندوراس') ,
            array('country_code' => 'HK', 'country_name' => 'هونغ كونغ') ,
            array('country_code' => 'HU', 'country_name' => 'هنغاريا'),
            array('country_code' => 'IS', 'country_name' => 'أيسلندا'),
            array('country_code' => 'IN', 'country_name' => 'الهند'),
            array('country_code' => 'ID', 'country_name' => 'إندونيسيا'),
            array('country_code' => 'IR', 'country_name' => 'جمهورية إيران الإسلامية') ,
            array('country_code' => 'IQ', 'country_name' => 'العراق'),
            array('country_code' => 'IE', 'country_name' => 'أيرلندا') ,
            array('country_code' => 'IL', 'country_name' => 'إسرائيل'),
            array('country_code' => 'IT', 'country_name' => 'إيطاليا'),
            array('country_code' => 'CI', 'country_name' => 'ساحل العاج'),
            array('country_code' => 'JM', 'country_name' => 'جامايكا') ,
            array('country_code' => 'JP', 'country_name' => 'اليابان'),
            array('country_code' => 'JO', 'country_name' => 'الأردن'),
            array('country_code' => 'KZ', 'country_name' => 'كازاخستان') ,
            array('country_code' => 'KE', 'country_name' => 'كينيا') ,
            array('country_code' => 'KI', 'country_name' => 'كيريباتي') ,
            array('country_code' => 'KP', 'country_name' => 'كوريا, الجمهورية الشعبية الديمقراطية'),
            array('country_code' => 'KR', 'country_name' => 'جمهورية كوريا'),
            array('country_code' => 'KW', 'country_name' => 'الكويت'),
            array('country_code' => 'KG', 'country_name' => 'قيرغيزستان') ,
            array('country_code' => 'LA', 'country_name' => 'جمهورية لاو الديمقراطية الشعبية') ,
            array('country_code' => 'LV', 'country_name' => 'لاتفيا') ,
            array('country_code' => 'LB', 'country_name' => 'لبنان') ,
            array('country_code' => 'LS', 'country_name' => 'ليسوتو') ,
            array('country_code' => 'LR', 'country_name' => 'ليبيريا') ,
            array('country_code' => 'LY', 'country_name' => 'الجماهيرية العربية الليبية'),
            array('country_code' => 'LI', 'country_name' => 'ليختنشتاين') ,
            array('country_code' => 'LT', 'country_name' => 'ليتوانيا') ,
            array('country_code' => 'LU', 'country_name' => 'لوكسمبورغ') ,
            array('country_code' => 'MO', 'country_name' => 'ماكاو') ,
            array('country_code' => 'MK', 'country_name' => 'مقدونيا') ,
            array('country_code' => 'MG', 'country_name' => 'مدغشقر') ,
            array('country_code' => 'MW', 'country_name' => 'ملاوي') ,
            array('country_code' => 'MY', 'country_name' => 'ماليزيا') ,
            array('country_code' => 'MV', 'country_name' => 'جزر المالديف') ,
            array('country_code' => 'ML', 'country_name' => 'مالي') ,
            array('country_code' => 'MT', 'country_name' => 'مالطا') ,
            array('country_code' => 'MH', 'country_name' => 'جزر مارشال') ,
            array('country_code' => 'MQ', 'country_name' => 'مارتينيك') ,
            array('country_code' => 'MR', 'country_name' => 'موريتانيا') ,
            array('country_code' => 'MU', 'country_name' => 'موريشيوس') ,
            array('country_code' => 'TY', 'country_name' => 'مايوت') ,
            array('country_code' => 'MX', 'country_name' => 'المكسيك') ,
            array('country_code' => 'FM', 'country_name' => 'ميكرونيزيا , ولايات الموحدة') ,
            array('country_code' => 'MD', 'country_name' => 'جمهورية مولدوفا'),
            array('country_code' => 'MC', 'country_name' => 'موناكو') ,
            array('country_code' => 'MN', 'country_name' => 'منغوليا') ,
            array('country_code' => 'MS', 'country_name' => 'مونتسيرات') ,
            array('country_code' => 'MA', 'country_name' => 'المغرب'),
            array('country_code' => 'MZ', 'country_name' => 'موزمبيق') ,
            array('country_code' => 'MM', 'country_name' => 'ميانمار') ,
            array('country_code' => 'NA', 'country_name' => 'ناميبيا') ,
            array('country_code' => 'NR', 'country_name' => 'ناورو') ,
            array('country_code' => 'NP', 'country_name' => 'نيبال') ,
            array('country_code' => 'NL', 'country_name' => 'هولندا'),
            array('country_code' => 'AN', 'country_name' => 'جزر الأنتيل الهولندية'),
            array('country_code' => 'NC', 'country_name' => 'كاليدونيا الجديدة'),
            array('country_code' => 'NZ', 'country_name' => 'نيوزيلندا'),
            array('country_code' => 'NI', 'country_name' => 'نيكاراغوا') ,
            array('country_code' => 'NE', 'country_name' => 'النيجر') ,
            array('country_code' => 'NG', 'country_name' => 'نيجيريا') ,
            array('country_code' => 'NU', 'country_name' => 'نيوي') ,
            array('country_code' => 'NF', 'country_name' => 'جزيرة نورفورك') ,
            array('country_code' => 'MP', 'country_name' => 'جزر مريانا الشمالية'),
            array('country_code' => 'NO', 'country_name' => 'النرويج'),
            array('country_code' => 'OM', 'country_name' => 'سلطنة عمان'),
            array('country_code' => 'PK', 'country_name' => 'باكستان') ,
            array('country_code' => 'PW', 'country_name' => 'بالاو') ,
            array('country_code' => 'PA', 'country_name' => 'بنما') ,
            array('country_code' => 'PG', 'country_name' => 'بابوا غينيا الجديدة') ,
            array('country_code' => 'PY', 'country_name' => 'باراغواي') ,
            array('country_code' => 'PE', 'country_name' => 'بيرو'),
            array('country_code' => 'PH', 'country_name' => 'الفلبين') ,
            array('country_code' => 'PN', 'country_name' => 'بيتكيرن') ,
            array('country_code' => 'PL', 'country_name' => 'بولندا'),
            array('country_code' => 'PT', 'country_name' => 'البرتغال'),
            array('country_code' => 'PR', 'country_name' => 'بورتوريكو') ,
            array('country_code' => 'QA', 'country_name' => 'دولة قطر'),
            array('country_code' => 'SS', 'country_name' => 'جمهورية جنوب السودان') ,
            array('country_code' => 'RE', 'country_name' => 'جمع شمل'),
            array('country_code' => 'RO', 'country_name' => 'رومانيا'),
            array('country_code' => 'RU', 'country_name' => 'الاتحاد الروسي') ,
            array('country_code' => 'RW', 'country_name' => 'رواندا') ,
            array('country_code' => 'KN', 'country_name' => 'سانت كيتس ونيفيس'),
            array('country_code' => 'LC', 'country_name' => 'القديسة لوسيا'),
            array('country_code' => 'VC', 'country_name' => 'سانت فنسنت وجزر غرينادين'),
            array('country_code' => 'WS', 'country_name' => 'ساموا') ,
            array('country_code' => 'SM', 'country_name' => 'سان مارينو'),
            array('country_code' => 'ST', 'country_name' => 'ساو تومي وبرينسيبي') ,
            array('country_code' => 'SA', 'country_name' => 'المملكة العربية السعودية'),
            array('country_code' => 'SN', 'country_name' => 'السنغال'),
            array('country_code' => 'RS', 'country_name' => 'صربيا') ,
            array('country_code' => 'SC', 'country_name' => 'سيشيل') ,
            array('country_code' => 'SL', 'country_name' => 'سيرا ليون'),
            array('country_code' => 'SG', 'country_name' => 'سنغافورة') ,
            array('country_code' => 'SK', 'country_name' => 'سلوفاكيا') ,
            array('country_code' => 'SI', 'country_name' => 'سلوفينيا') ,
            array('country_code' => 'SB', 'country_name' => 'جزر سليمان'),
            array('country_code' => 'SO', 'country_name' => 'الصومال'),
            array('country_code' => 'ZA', 'country_name' => 'جنوب أفريقيا'),
            array('country_code' => 'GS', 'country_name' => 'جزر جورجيا الجنوبية ساندويتش') ,
            array('country_code' => 'ES', 'country_name' => 'إسبانيا'),
            array('country_code' => 'LK', 'country_name' => 'سيريلانكا'),
            array('country_code' => 'SH', 'country_name' => 'سانت هيلينا') ,
            array('country_code' => 'PM', 'country_name' => 'سانت بيير وميكلون') ,
            array('country_code' => 'SD', 'country_name' => 'السودان'),
            array('country_code' => 'SJ', 'country_name' => 'جزر سفالبارن وجان مايان') ,
            array('country_code' => 'SZ', 'country_name' => 'سوازيلاند') ,
            array('country_code' => 'SE', 'country_name' => 'السويد'),
            array('country_code' => 'CH', 'country_name' => 'سويسرا') ,
            array('country_code' => 'SY', 'country_name' => 'الجمهورية العربية السورية'),
            array('country_code' => 'TW', 'country_name' => 'تايوان') ,
            array('country_code' => 'TJ', 'country_name' => 'طاجيكستان') ,
            array('country_code' => 'TZ', 'country_name' => 'جمهورية تنزانيا المتحدة') ,
            array('country_code' => 'TH', 'country_name' => 'تايلاند') ,
            array('country_code' => 'TG', 'country_name' => 'توجو'),
            array('country_code' => 'TK', 'country_name' => 'توكيلاو') ,
            array('country_code' => 'TO', 'country_name' => 'تونغا') ,
            array('country_code' => 'TT', 'country_name' => 'ترينداد وتوباغو'),
            array('country_code' => 'TN', 'country_name' => 'تونس') ,
            array('country_code' => 'TR', 'country_name' => 'ديك رومي'),
            array('country_code' => 'TM', 'country_name' => 'تركمانستان') ,
            array('country_code' => 'TC', 'country_name' => 'جزر تركس وكايكوس'),
            array('country_code' => 'TV', 'country_name' => 'توفالو') ,
            array('country_code' => 'UG', 'country_name' => 'أوغندا') ,
            array('country_code' => 'UA', 'country_name' => 'أوكرانيا') ,
            array('country_code' => 'AE', 'country_name' => 'الإمارات العربية المتحدة'),
            array('country_code' => 'GB', 'country_name' => 'المملكة المتحدة'),
            array('country_code' => 'UM', 'country_name' => 'جزر الولايات المتحدة البعيدة الصغرى'),
            array('country_code' => 'UY', 'country_name' => 'أوروغواي') ,
            array('country_code' => 'UZ', 'country_name' => 'أوزبكستان') ,
            array('country_code' => 'VU', 'country_name' => 'فانواتو') ,
            array('country_code' => 'VA', 'country_name' => 'دولة مدينة الفاتيكان') ,
            array('country_code' => 'VE', 'country_name' => 'فنزويلا') ,
            array('country_code' => 'VN', 'country_name' => 'فيتنام') ,
            array('country_code' => 'VG', 'country_name' => 'جزر العذراء البريطانية)'),
            array('country_code' => 'VI', 'country_name' => 'جزر فيرجن (الولايات المتحدة)') ,
            array('country_code' => 'WF', 'country_name' => 'جزر واليس وفوتونا') ,
            array('country_code' => 'EH', 'country_name' => 'الصحراء الغربية'),
            array('country_code' => 'YE', 'country_name' => 'اليمن'),
            array('country_code' => 'YU', 'country_name' => 'يوغوسلافيا') ,
            array('country_code' => 'ZR', 'country_name' => 'زائير') ,
            array('country_code' => 'ZM', 'country_name' => 'زامبيا') ,
            array('country_code' => 'ZW', 'country_name' => 'زيمبابوي') ,
        );

      
         DB::table('countries')->insert($countries);
    }
}
